# Generated by Django 5.2.16 on 2026-07-09 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=200)),
                ('zip', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='carmake',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='dealer_id',
        ),
        migrations.AlterField(
            model_name='carmake',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.carmake'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('review', models.TextField()),
                ('car_make', models.CharField(default='', max_length=100)),
                ('car_model', models.CharField(default='', max_length=100)),
                ('car_year', models.IntegerField(default=2023)),
                ('sentiment', models.CharField(default='neutral', max_length=50)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.dealer')),
            ],
        ),
    ]
