# Generated by Django 5.2.15 on 2026-07-05 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='carmake',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='carmake',
            name='description',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='dealer_id',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='year',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.carmake'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.dealer')),
            ],
        ),
    ]
